nlu:
- intent: opening
  examples:
  - text: |
      hello

- intent: initialgreeting
  examples:
  - text: |
      hello

- intent: offer
  examples:
  - text: |
      can I help you

- intent: acceptoffer
  examples:
  - text: |
      yes

- intent: inform_continue
  examples:
  - text: |
      in Avon I want to load three box- drop off the one engine drop off the two tankers of OJ
  - text: |
      the two tankers
  - text: |
      I have a problem I need to transport two tankers of OJ to Avon and three boxcars of bananas to Elmira
  - text: |
      two tankers of OJ to Avon would mean I take engine two and take the two b(oxcars)- from Elmira and bring them over and pick up two and bring them back to Elmira to fill with OJ
  - text: |
      and I can only use engine two it's all the way over here

- intent: inform_pass
  examples:
  - text: |
      I can only use engine two
  - text: |
      the bananas must arrive in Elmira by nine p.m.
  - text: |
      when I reach Dansville I wanna pick up one more boxcar
  - text: |
      load those three
  - text: |
      it's now noon when you arrive in Avon
  - text: |
      I guess I still have nine hours
  - text: |
      bring it with me with the other two to Avon

- intent: autopositive
  examples:
  - text: |
      okay
  - text: |
      okay then that way
  - text: |
      okay
    metadata:
      turnManagement: turnTake
  - text: |
      mm-hm
  - text: |
      okay that's fine

- intent: stalling
  examples:
  - text: |
      VOC mumble .. VOC click ..
  - text: |
      um
    metadata:
      turnManagement: turnTake
  - text: |
      when I reach, when I reach
  - text: |
      uh
    metadata:
      turnManagement: turnTake
  - text: |
      so … VOC noise
    metadata:
      turnManagement: turnTake
  - text: |
      t(o)-
  - text: |
      f- .. uh
    metadata:
      turnManagement: turnTake
  - text: |
      uh …
    metadata:
      turnManagement: turnAccept
  - text: |
      and ..
    metadata:
      turnManagement: turnKeep

- intent: propositionalquestion
  examples:
  - text: |
      do you wanna load the boxcars while you're in Corning

- intent: answer
  examples:
  - text: |
      to Corning
  - text: |
      I will take them with me
  - text: |
      yes
  - text: |
      yeah to Corning to Dansville to Avon

- intent: instruct
  examples:
  - text: |
      then make the OJ in Elmira with engine two and take it from Elmira to Corning to Dansville to Avon

- intent: choicequestion
  examples:
  - text: |
      do you wanna take the boxcars with you or do you want to leave them in Elmira
    metadata:
      turnManagement: turnAssign

- intent: checkquestion
  examples:
  - text: |
      so you wanna go from Elmira

- intent: completion
  examples:
  - text: |
      to Avon

- intent: setquestion
  examples:
  - text: |
      by which way

- intent: pausing
  examples:
  - text: |
      oh oh wait
  - text: |
      let me think
  - text: |
      let me see

- intent: inform
  examples:
  - text: |
      I have something else to say

- intent: selfcorrection
  examples:
  - text: |
      the one tanker the two tankers
  - text: |
      I when I hit- when I reach
  - text: |
      the two tankers
  - text: |
      of oranges and of OJ actually

