nlu:
- intent: opening
  examples:
  - text: |
      hello

- intent: offer
  examples:
  - text: |
      can I help you

- intent: acceptoffer
  examples:
  - text: |
      yes

- intent: inform_pass
  examples:
  - text: |
      then I'll take engine E two
  - text: |
      then I'd like to take the tanker of orange juice through Dansville and then on to Avon
  - text: |
      I'd like to take a tanker from Corning and bring it to Elmira
  - text: |
      and from Elmira I'd like to load orange juice into the tanker

- intent: autopositive
  examples:
  - text: |
      alright
  - text: |
      mm-hm
  - text: |
      okay

- intent: inform_continue
  examples:
  - text: |
      I'd like then to take the tanker back from Elmira to Corning

- intent: stalling
  examples:
  - text: |
      um
    metadata:
      turnManagement: turnKeep
  - text: |
      well
    metadata:
      turnManagement: turnTake
  - text: |
      the the
  - text: |
      uh

- intent: setquestion
  examples:
  - text: |
      the tankers move at the same speed
  - text: |
      which engine would you like to use
  - text: |
      now from Corning what would be the quickest route to Avon

- intent: answer
  examples:
  - text: |
      engine E two
  - text: |
      no they're both the same
  - text: |
      through Dansville

- intent: propositionalquestion
  examples:
  - text: |
      will either one take me there any quicker

- intent: selfcorrection
  examples:
  - text: |
      they're a they're

