nlu:
- intent: opening
  examples:
  - text: |
      hello

- intent: initialGreeting
  examples:
  - text: |
      hello

- intent: offer
  examples:
  - text: |
      can I help you

- intent: acceptOffer
  examples:
  - text: |
      yes

- intent: inform_continue
  examples:
  - text: |
      two tankers of OJ to Avon would mean I take engine two and take the two b(oxcars)- from Elmira and bring them over and pick up two and bring them back to Elmira to fill with OJ
  - text: |
      I have a problem I need to transport two tankers of OJ to Avon and three boxcars of bananas to Elmira
  - text: |
      in Avon I want to load three box- drop off the one engine drop off the two tankers of OJ
  - text: |
      and I can only use engine two it's all the way over here
  - text: |
      the two tankers

- intent: inform_pass
  examples:
  - text: |
      when I reach Dansville I wanna pick up one more boxcar
  - text: |
      I guess I still have nine hours
  - text: |
      I can only use engine two
  - text: |
      load those three
  - text: |
      bring it with me with the other two to Avon
  - text: |
      it's now noon when you arrive in Avon
  - text: |
      the bananas must arrive in Elmira by nine p.m.

- intent: autoPositive
  examples:
  - text: |
      okay then that way
  - text: |
      okay that's fine
  - text: |
      okay
  - text: |
      okay
    metadata:
      turnManagement: turnTake
  - text: |
      mm-hm

- intent: stalling
  examples:
  - text: |
      uh …
    metadata:
      turnManagement: turnAccept
  - text: |
      t(o)-
  - text: |
      so … VOC noise
    metadata:
      turnManagement: turnTake
  - text: |
      f- .. uh
    metadata:
      turnManagement: turnTake
  - text: |
      um
    metadata:
      turnManagement: turnTake
  - text: |
      and ..
    metadata:
      turnManagement: turnKeep
  - text: |
      when I reach, when I reach
  - text: |
      uh
    metadata:
      turnManagement: turnTake
  - text: |
      VOC mumble .. VOC click ..

- intent: propositionalQuestion
  examples:
  - text: |
      do you wanna load the boxcars while you're in Corning

- intent: answer
  examples:
  - text: |
      yeah to Corning to Dansville to Avon
  - text: |
      to Corning
  - text: |
      I will take them with me
  - text: |
      yes

- intent: instruct
  examples:
  - text: |
      then make the OJ in Elmira with engine two and take it from Elmira to Corning to Dansville to Avon

- intent: choiceQuestion
  examples:
  - text: |
      do you wanna take the boxcars with you or do you want to leave them in Elmira
    metadata:
      turnManagement: turnAssign

- intent: checkQuestion
  examples:
  - text: |
      so you wanna go from Elmira

- intent: completion
  examples:
  - text: |
      to Avon

- intent: setQuestion
  examples:
  - text: |
      by which way

- intent: pausing
  examples:
  - text: |
      let me see
  - text: |
      oh oh wait
  - text: |
      let me think

- intent: inform
  examples:
  - text: |
      I have something else to say

- intent: selfCorrection
  examples:
  - text: |
      the one tanker the two tankers
  - text: |
      the two tankers
  - text: |
      of oranges and of OJ actually
  - text: |
      I when I hit- when I reach

