nlu:
- intent: opening
  examples:
  - text: |
      hello

- intent: initialgreeting
  examples:
  - text: |
      hello

- intent: offer
  examples:
  - text: |
      can I help you

- intent: acceptoffer
  examples:
  - text: |
      yeah

- intent: stalling
  examples:
  - text: |
      VOC_breath so VOC_breath
    metadata:
      turnManagement: turnKeep
  - text: |
      VOC_breath
    metadata:
      turnManagement: turnKeep
  - text: |
      ... um
    metadata:
      turnManagement: turnKeep
  - text: |
      VOC_breath hm ... so
  - text: |
      um
    metadata:
      turnManagement: turnKeep
  - text: |
      VOC_breath
  - text: |
      I want t-
  - text: |
      ... hm so

- intent: inform_continue
  examples:
  - text: |
      we have the three boxcars at Dansville
  - text: |
      I want to determine the maximum number of boxcars of oranges that I can get to Bath by seven a.m. tomorrow
  - text: |
      we can unload any amount of cargo onto a train in one hour
  - text: |
      I guess all the boxcars will have to go through Corning
  - text: |
      but the thing is that I was thinking if we could actually pick up those two boxcars which are at Bath
  - text: |
      but I think that we can't even put them in to
  - text: |
      so we're like screwed as far as those two box cars at Bath
  - text: |
      we could actually take like engine E
  - text: |
      like I don't think we so to get the maximum number of box cars of oranges to bath by seven am I don't think we can even use those two at Bath
  - text: |
      because that's where the orange juice factory is
  - text: |
      that they won't even come in to
  - text: |
      have it go to Bath pick up those two box cars

- intent: selfcorrection
  examples:
  - text: |
      to Corning
  - text: |
      orange factory
  - text: |
      that they won't even come in to

- intent: setquestion
  examples:
  - text: |
      how long from Bath to Corning
  - text: |
      from Corning to Bath how far is that
    metadata:
      turnManagement: turnAssign
  - text: |
      how far is it from Avon to Danville
  - text: |
      how far is it from Avon to Bath
  - text: |
      I thought well from like Elmira through to Corning to Bath is many hours
  - text: |
      how far is it from Elmira to Bath VOC_breath

- intent: answer
  examples:
  - text: |
      that's six hours 
  - text: |
      four hours
  - text: |
      two hours
  - text: |
      one hour
  - text: |
      three hours

- intent: checkquestion
  examples:
  - text: |
      an hour I guess
  - text: |
      so we can actually use those three boxcars right
    metadata:
      turnManagement: turnAssign
  - text: |
      and it's gonna take us also an hour to load boxcars right
    metadata:
      turnManagement: turnAssign
  - text: |
      every trip will take at least three hours then

- intent: confirm
  examples:
  - text: |
      right
  - text: |
      mm-hm

- intent: autopositive
  examples:
  - text: |
      okay
  - text: |
      oh wait a second
  - text: |
      oh that's four hours
  - text: |
      right
  - text: |
      mm
  - text: |
      VOC_click VOC_breath
    metadata:
      turnManagement: turnTake
  - text: |
      from Avon
  - text: |
      okay
    metadata:
      turnManagement: turnTake
  - text: |
      three hours
  - text: |
      oh really

- intent: inform_pass
  examples:
  - text: |
      we can do a maximum of three boxcars in an hour
  - text: |
      it's shorter through Dansville
  - text: |
      because we can't get an engine to Bath in time

- intent: suggest
  examples:
  - text: |
      I guess one thing we can do
  - text: |
      I guess one thing is that we should see how many boxcars we can actually get to Corning in four hours

- intent: selferror
  examples:
  - text: |
      oh no
  - text: |
      oh

- intent: retraction
  examples:
  - text: |
      take it to Corn-
  - text: |
      unless

- intent: agreement
  examples:
  - text: |
      that's right

- intent: setquestion
  examples:
  - text: |
      then from Dansville to Corning

